Try making @mikroskeem happier
inoda/journal pull request #38
Opened 2022-02-19 22:00 UTC by jtagcat

Closes #37

2022-02-19 22:31 UTC, mikroskeem commented
pls

2022-02-27 01:00 UTC, inoda commented on docker-compose.yml
> +      - /media/jc/floppy/jounral/data:/app:rw
Is there a typo here? Should this say `journal`?

2022-02-27 01:01 UTC, inoda commented on docker-compose.yml
> +      - POSTGRES_USER=rahvakunst
Same thing here re: replacing `rahvakunst` and `kebab`

2022-02-27 01:01 UTC, inoda requested changes
Left a few comments

2022-02-27 19:23 UTC, inoda commented on docker-compose.yml
> +      - DATABASE_URL=postgres://replaceme:RePLAcEpAsS@journal-db/kebab
what is `kebab`?

2022-02-27 19:23 UTC, inoda commented on docker-compose.yml
> +      - POSTGRES_DB=kebab
same here - what is `kebab`?

2022-02-27 19:24 UTC, inoda requested changes
still some strange placeholders

2022-02-27 19:41 UTC, mikroskeem commented on docker-compose.yml
> +      - DATABASE_URL=postgres://replaceme:RePLAcEpAsS@journal-db/kebab
https://en.wikipedia.org/wiki/Kebab

I believe @jtagcat is trying to introduce better words than `foo`, `bar` and `baz`.

2022-03-28 00:12 UTC, wi0001 commented
🤔 🚀

2022-03-31 02:00 UTC, merged